---
apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  labels:
    prometheus: apps
  name: statuscope-checks
spec:
  groups:
  - name: pitc-statuscope-prod_alerts
    rules:
    - alert: statuscope outdated
      annotations:
        summary: Der Check {{ $labels.application }} ist veraltet.
      expr: statuscope_check_ok{namespace="pitc-statuscope-prod"} == 2
      labels:
        rocketchat_channel: '#devruby-alerts'
        severity: critical
        instance: '{{ $labels.application }}'
    - alert: statuscope fail
      annotations:
        summary: Der Check {{ $labels.application }} ist fehlgeschlagen.
      expr: statuscope_check_ok{namespace="pitc-statuscope-prod"} == 3
      labels:
        rocketchat_channel: '#devruby-alerts'
        severity: critical
        instance: '{{ $labels.application }}'
