apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  name: statuscope
spec:
  lookupPolicy:
    local: true
  tags:
  - from:
      kind: DockerImage
      name: REGISTRY/IMAGE:TAG
    importPolicy:
      importMode: Legacy
    name: latest
    referencePolicy:
      type: Source
