kind: ImageStream
apiVersion: v1
metadata:
  name: statuscope
spec:
  lookupPolicy:
    local: true
---
kind: BuildConfig
apiVersion: v1
metadata:
  name: statuscope
spec:
  successfulBuildsHistoryLimit: 3
  output:
    to:
      kind: ImageStreamTag
      name: statuscope:latest
  resources:
    limits:
      cpu: 1
      memory: 2Gi
    requests:
      cpu: 100m
      memory: 128Mi
  source:
    type: Git
    git:
      uri: https://github.com/puzzle/statuscope.git
      ref: v1.2.1
  strategy:
    type: Docker
    dockerStrategy:
      dockerfilePath: Dockerfile
      from:
        kind: ImageStreamTag
        name: ruby:3.0
      buildArgs:
      - name: BUILD_PACKAGES
        value: "sqlite3 libsqlite3-dev build-essential"
      - name: RUN_PACKAGES


---
apiVersion: v1
kind: ImageStream
metadata:
  name: ruby-upstream
  annotations:
    puzzle.ch/purpose: Upstream image change trigger
spec:
  dockerImageRepository: docker.io
  tags:
    - from:
        kind: DockerImage
        name: docker.io/ruby:3.0
      importPolicy:
        scheduled: true
      name: latest
  lookupPolicy:
    local: true
...
